// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	storage "github.com/ElOtro/go-metrics/internal/repo/storage"
	mock "github.com/stretchr/testify/mock"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

// Get provides a mock function with given fields: t, n
func (_m *Repo) Get(t string, n string) (*storage.Metrics, error) {
	ret := _m.Called(t, n)

	var r0 *storage.Metrics
	if rf, ok := ret.Get(0).(func(string, string) *storage.Metrics); ok {
		r0 = rf(t, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.Metrics)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(t, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHealth provides a mock function with given fields:
func (_m *Repo) GetHealth() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMetricsByID provides a mock function with given fields: id, mtype
func (_m *Repo) GetMetricsByID(id string, mtype string) (*storage.Metrics, error) {
	ret := _m.Called(id, mtype)

	var r0 *storage.Metrics
	if rf, ok := ret.Get(0).(func(string, string) *storage.Metrics); ok {
		r0 = rf(id, mtype)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.Metrics)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, mtype)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields:
func (_m *Repo) List() ([]*storage.Metrics, error) {
	ret := _m.Called()

	var r0 []*storage.Metrics
	if rf, ok := ret.Get(0).(func() []*storage.Metrics); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.Metrics)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestoreMetrics provides a mock function with given fields: filename
func (_m *Repo) RestoreMetrics(filename string) error {
	ret := _m.Called(filename)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(filename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Set provides a mock function with given fields: t, n, v
func (_m *Repo) Set(t string, n string, v string) error {
	ret := _m.Called(t, n, v)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(t, n, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetMetrics provides a mock function with given fields: _a0
func (_m *Repo) SetMetrics(_a0 *storage.Metrics) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*storage.Metrics) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepo(t mockConstructorTestingTNewRepo) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
